site_name: RedisGraph - a graph database module for Redis
site_url: http://redisgraph.io
repo_url: https://github.com/RedisGraph/RedisGraph
repo_name: RedisGraph/RedisGraph

google_analytics:
  - 'UA-92003007-1'
  - 'auto'

extra_javascript:
  - gtm.js

use_directory_urls: true

theme:
  name: 'material'
  language: 'en'
  logo: 'images/logo_small.png'
  favicon: 'images/favicon.png'
  palette:
    primary: 'indigo'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false

nav:
  - 'Quickstart': index.md
  - 'Commands': commands.md
  - 'Clients': clients.md
  - 'Configuration': configuration.md
  - 'Design Documents':
      - 'Result Set structure': result_structure.md
      - 'Client Specification': client_spec.md
  - 'Design': design.md
  - 'Contributor agreement': contrib.md
  - 'Cypher coverage': cypher_support.md
  - 'References': References.md
  - 'Known limitations': known_limitations.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - toc:
      permalink: True

plugins:
  - search
  - versions-menu

