site_name: RedisGraph - a graph database module for Redis
site_url: http://redisgraph.io
repo_url: https://github.com/RedisGraph/RedisGraph
repo_name: RedisGraph/RedisGraph

google_analytics:
  - 'UA-92003007-1'
  - 'auto'

use_directory_urls: true

theme:
  name: 'material'
  language: 'en'
  logo: 'images/logo_small.png'
  favicon: 'images/favicon.png'
  palette:
    primary: 'indigo'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false

pages:
    - 'Quickstart': index.md
    - 'Downloads': download.md
    - 'Commands': commands.md
    - 'Design': design.md
    - 'Contributor agreement': contrib.md
    - 'Cypher coverage': cypher_support.md
    - 'Known limitations': known_limitations.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - toc:
      permalink: True
