name: Build on ubuntu

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: swilly22/falkordb-build:latest
    steps:

    - name: Safe dir
      run: git config --global --add safe.directory '*'

    - uses: actions/checkout@v3
      with:
        set-safe-directory: '*'
        submodules: recursive

    - name: Cache GraphBLAS
      id: cache_graphblas
      uses: actions/cache@v3
      with:
        path: /FalkorDB/bin/linux-x64-release/GraphBLAS
        key: graphblas-${{ hashFiles('./deps/GraphBLAS/Include/GraphBLAS.h') }}    

    - name: Cache parser
      id: cache_parser
      uses: actions/cache@v3
      with:
        path: /FalkorDB/bin/linux-x64-release/libcypher-parser
        key: parser-${{ hashFiles('./deps/libcypher-parser/lib/src/parser.c') }}

    - name: Cache search
      id: cache_search
      uses: actions/cache@v3
      with:
        path: /FalkorDB/bin/linux-x64-release/search-static
        key: search-${{ hashFiles('./deps/RediSearch/src/version.h') }}

    # Make sure the working directory is static between runs 
    # and always the same for the CMake cache
    - name: Relocate source
      run: |
        mkdir -p /FalkorDB
        mv $GITHUB_WORKSPACE/* /FalkorDB

    - name: Build
      working-directory: /FalkorDB
      run: make

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: /FalkorDB
        file: /FalkorDB/build/docker/Dockerfile
        push: true
        tags: falkordb/falkordb:${{ github.ref_name == 'master' && 'master,falkordb/falkordb:edge' || github.ref_name  }}

  unit-tests:
    runs-on: ubuntu-latest
    container: falkordb/falkordb:${{ github.ref_name }}
    needs: build
    steps:
      - name: Unit tests
        working-directory: /FalkorDB
        run: make unit-tests CLEAR_LOGS=0

  flow-tests:
    runs-on: ubuntu-latest
    container: falkordb/falkordb:${{ github.ref_name }}
    needs: build
    steps:
      - name: Flow tests
        working-directory: /FalkorDB
        run: make CLEAR_LOGS=0 PARALLEL=4 flow-tests

  tck-tests:
    runs-on: ubuntu-latest
    container: falkordb/falkordb:${{ github.ref_name }}
    needs: build
    steps:
      - name: TCK tests
        working-directory: /FalkorDB
        run: make CLEAR_LOGS=0 tck-tests

  fuzz-tests:
    runs-on: ubuntu-latest
    container: falkordb/falkordb:${{ github.ref_name }}
    needs: build
    steps:
      - name: Fuzz tests
        working-directory: /FalkorDB
        run: make fuzz TIMEOUT=180
