name: Sanitizer

on:
  push:
  workflow_dispatch:

jobs:
  sanitize-test:
    runs-on: ubuntu-latest
    container: swilly22/falkordb-build:latest
    steps:

    - name: Safe dir
      run: git config --global --add safe.directory '*'

    - uses: actions/checkout@v3
      with:
        set-safe-directory: '*'
        submodules: recursive

    - name: Cache GraphBLAS
      id: cache_graphblas
      uses: actions/cache@v3
      with:
        path: ./bin/linux-x64-debug-asan/GraphBLAS
        key: graphblas-sanitizer-${{ hashFiles('./deps/GraphBLAS/Include/GraphBLAS.h') }}

    - name: Cache parser
      id: cache_parser
      uses: actions/cache@v3
      with:
        path: ./bin/linux-x64-debug-asan/libcypher-parser
        key: parser-sanitizer-${{ hashFiles('./deps/libcypher-parser/lib/src/parser.c') }}

    - name: Cache search
      id: cache_search
      uses: actions/cache@v3
      with:
        path: ./bin/linux-x64-debug-asan/search-static
        key: search-sanitizer-${{ hashFiles('./deps/RediSearch/src/version.h') }}

    - name: Build
      run: make CLANG=1 SAN=address NPROC=16

    - name: Unit tests
      run: make unit-tests CLEAR_LOGS=0 SAN=address
      continue-on-error: true

    - uses: actions/upload-artifact@v3
      with:
        name: Upload unit tests logs
        path: ${{ github.workspace }}/tests/unit/logs/
        retention-days: 7

    - name: Flow tests
      run: make flow-tests CLEAR_LOGS=0 SAN=address
      continue-on-error: true

    - uses: actions/upload-artifact@v3
      with:
        name: Upload flow tests logs
        path: ${{ github.workspace }}/tests/flow/logs/
        retention-days: 7

    - name: TCK tests
      run: make tck-tests CLEAR_LOGS=0 SAN=address

    - uses: actions/upload-artifact@v3
      with:
        name: Upload TCK tests logs
        path: ${{ github.workspace }}/tests/tck/logs/
        retention-days: 7
